### ISSUE TITLE
Provide a toolbar hook to edit namespace config

### ISSUE THREAD

**Issue by yakky** [aldryn/aldryn-apphooks-config#11]

**Comment by mkoistinen** [comment]
This already exists: 
![image](https://cloud.githubusercontent.com/assets/615759/6607103/a5b6df62-c812-11e4-99e1-4cb7c1b7ed92.png)

See the first item in the existing menu "Configure application ..."

**Comment by mkoistinen** [comment]
Just my 2 cents here. Perhaps this should be left to projects to implement –– or not?

In aldryn-newsblog, for example, we do this, but we have other things going on in the menu. If we implement a menu here, it should be extensible so that other app-related menu items can be added by the developer.

**Comment by yakky** [comment]
@mkoistinen agree

**Comment by yakky** [comment]
wontfix (see comments above)
