### ISSUE TITLE
adding best practice for defining config form and calling setup_config

### ISSUE THREAD

**Issue by benzkji** [aldryn/aldryn-apphooks-config#30]
as I got now, it's important that setup_config is called.

I suggest you add a short line into the readme that clarifies where this code should go. I first thought cms_appconfig.py has some magic detection, but it doesnt seem?

I now put mine into admin.py.

**Comment by yakky** [comment]
Fixed by PR.
``setup_config`` can stay in ``cms_appconfig.py``: being it imported in both ``models.py`` and ``admin.py`` the setup is guaranteed to be called
