### ISSUE TITLE
'NoneType' object has no attribute 'exclude_featured'

### ISSUE THREAD

**Issue by liminspace** [aldryn/aldryn-apphooks-config#47]
I get this error when I use `django-solid-i18n-urls`. Problem is in `get_app_instance` function.

aldryn-apphooks-config==0.3.0
Django==1.8.17
solid-i18n==1.4.0

**Comment by yakky** [comment]
@liminspace could you provide a more detailed traceback? `exclude_featured`is not an attribute called in this codebase, and probably it's triggered by some other compatibility issue

**Comment by liminspace** [comment]
Sorry, I can't now.
I think it was incompatibility between solid-i18n and aldryn-apphooks-config.
So I moved into django 1.10 and removed solid-i18n and the problem disappeared.

**Comment by yakky** [comment]
Closing this then.
Thanks for your feedback
