### ISSUE TITLE
build_attrs() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by AgaKorotkiewicz** [aldryn/aldryn-apphooks-config#52]
https://github.com/aldryn/aldryn-apphooks-config/blob/4c342cf93afb83de60828e946579e88e9d86822f/aldryn_apphooks_config/widgets.py#L18

There is an issue with _name_ parameter in _Django=1.11.x_  
because _build_attrs_ method does not have this input parameter:
https://github.com/django/django/blob/58f02c498b659a906e9c30d946bd89bedc4717e5/django/forms/widgets.py#L228

Current code raises 
> TypeError: build_attrs() got an unexpected keyword argument 'name'

aldryn-apphooks-config==0.3.3
django=1.11.2

**Comment by bxm156** [comment]
I'm see thins as well. the django-sortedm2m project had a simliar issue and had to fixed. And example is at 
https://github.com/gregmuellegger/django-sortedm2m/pull/108/files. That PR wasn't pulled in, but the fix should be the same as what was eventualled pulled in https://github.com/gregmuellegger/django-sortedm2m/pull/104/files

**Comment by bbirand** [comment]
I get this too.

**Comment by yakky** [comment]
We need to fix this in django-appdata before we can complete the django 1.11 support in this one
@czpython could you have a look at https://github.com/ella/django-appdata/pull/20
It appears to bring full Django 1.11 support and I think we should complete the 1.11 support across the entire ecosystem

**Comment by jedie** [comment]
Me, too :(

**Comment by yakky** [comment]
We are doing the last checks on #54 which will bring full compatibility

**Comment by yakky** [comment]
@AgaKorotkiewicz thanks again for reporting this.
It's been fixed in #54
Happy to announce that a new release is coming really soon!
