### ISSUE TITLE
Error when using prepopulated_fields with ModelAppHookConfig

### ISSUE THREAD

**Issue by TheDeadOne** [aldryn/aldryn-apphooks-config#60]
When I try to use something like this

```
@admin.register(SomeModel)
class SomeModelAdmin(ModelAppHookConfig, admin.ModelAdmin):
    prepopulated_fields = {
        'slug': ('title',)
    }
```

I get an error "Key 'slug' not found in 'InitialForm'. Choices are: app_config."

**Comment by yakky** [comment]
@TheDeadOne use `get_prepopulated_fields`, django-appdata does not allow using `prepopulated_fields` attribute

**Comment by TheDeadOne** [comment]
Thank you.
